### ISSUE TITLE
Compiled files different in pure Julia 

### ISSUE THREAD

**Issue by matthewware** [BBN-Q/QGL.jl#14]
Compiled files for control of the qubit are smaller in the pure Julia version of the code @e26357b than in the PyCall QGL version @daff1c9.  In the most recent version of GST experiments this translates into a ~15% difference in .h5 file size.

**Comment by caryan** [comment]
seems worrisome.....

**Comment by caryan** [comment]
I'm quite sure the PyCall  changes were a red herring. If you're using `DiAC` pulses the difference is from b4cb74710d8c8e4ebb77b83199f0385ad8da287a where we elide noop  Z rotations  Previously ~11% of the instructions were noop Z rotations for 1Q GST with `DiAC` pulses. Before the change:

```julia

julia> seqs = create_1Q_GST_seqs("/home/cryan/Downloads/gst-1q-1024-r001.csv", q1);
julia> compile_to_hardware(seqs, "silly");
julia> instrs = h5read("silly-BBNAPS1.h5", "/chan_1/instructions")
5595177-element Array{UInt64,1}:
 0x9100800000000000
 0xa100270000000000
                  ⋮
julia> mod_instrs = filter(x -> ((x >> 60) & 0xf) == 0xa, instrs)
3979530-element Array{UInt64,1}:
 0xa100270000000000
 0xa100610005555555
 0xa100270000000000
                  ⋮
julia> frame_change_noops = filter(x -> (x & 0xffff_ffff) == 0, mod_instrs) 
652836-element Array{UInt64,1}:
 0xa100270000000000
 0xa100270000000000
                  ⋮

julia> length(frame_change_noops) / length(instrs)
0.11667834636866715

```
