### ISSUE TITLE
Extra finite Id after initial Z pulse

### ISSUE THREAD

**Issue by dieris** [BBN-Q/QGL.jl#18]
A sequence like
`[Z(q), X(q)]`
will compile with an additional `Id(q)` between the two pulses.

**Comment by caryan** [comment]
I'm pretty sure this is just from the slave trigger getting tensored onto the first sequence entry. If it's a `Pulse` or `PulseBlock` it's usually longer than the slave trigger and it you don't see any change in length but if the sequence starts with a `ZPulse` the length of the slave trigger gets inserted and shows up as an additional `Id(q)`

**Comment by caryan** [comment]
But I guess the point is we should be tensoring the slave trigger on a non-zero length pulse. We didn't have this problem in pyQGL because there are no zero length Z pulses

**Comment by caryan** [comment]
should be closed by b567f91
