### ISSUE TITLE
Delays for AWGs

### ISSUE THREAD

**Issue by dieris** [BBN-Q/QGL.jl#19]
Instrument delays must be inserted, in addition to the channel delays

**Comment by caryan** [comment]
at first it seemed annoying to bring the `Instrument.json` in too but we'll need it at some point to determine the type of AWG we are translating too

**Comment by caryan** [comment]
@dieris I'm pretty sure that AWG delays are not working in pyQGL either!

**Comment by caryan** [comment]
closed in 652b0c5
