### ISSUE TITLE
Modulation instructions for initial Z pulse

### ISSUE THREAD

**Issue by dieris** [BBN-Q/QGL.jl#20]
`MODULATE` and `UPDATE_FRAME` instructions should be applied before `WAIT` if the sequence starts with a `Z`. Otherwise, these instructions would be applied too late (after the next pulse).

**Comment by caryan** [comment]
We'll have to double check on the hardware w.r.t. to the `UPDATE_FRAME` because we also usually have a `RESET_PHASE` too. We may have to translate it to a `SET_FRAME`.

**Comment by caryan** [comment]
Hmmm, I was forgetting we don't have a  `SET_FRAME` command but the way the HDL works a reset followed by an `UPDATE_FRAME` will apply an initial Z pulse. The `MODULATE` instruction has to wait until after the `WAIT_FOR_TRIGGER` but it should be pipelined appropriately to line up with the first pulse starting.

**Comment by caryan** [comment]
Should be fixed by 1f0d87a
