### ISSUE TITLE
Wasteful use of memory in AC and DiAC functions

### ISSUE THREAD

**Issue by marcusps** [BBN-Q/QGL.jl#22]
@blakejohnson and @caryan can correct me if I am wrong, but I think redeclaring arrays of function and angles in the `AC` and `DiAC` methods leads to a lot of memory allocation and decallocation.

I suggest the static variable pattern, for example
```julia
begin 
  local pulses = [
		q -> Id(q),
		q -> X90(q),
		q -> X(q),
		q -> X90m(q),
		q -> Y90(q),
		q -> Y(q),
		q -> Y90m(q),
		q -> Z90(q),
		q -> Z(q),
		q -> Z90m(q)
	]
  global AC

  function AC(q::Qubit, num)
	return pulses[num](q)
  end

end
```

**Comment by blakejohnson** [comment]
I think I've already fixed this on the brj/review branch. I'm not 100% sure that Julia doesn't do this optimization for free. But in either case, it is better to simply make a list of function handles rather than anonymous functions.

**Comment by dieris** [comment]
Closed by https://github.com/BBN-Q/QGL.jl/pull/23
